name: buildlunahook
on:
  workflow_dispatch:

jobs:
  build_xp:
    runs-on: windows-latest
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 26100
      - run: python src/scripts/build_lunahook.py build x86 0 xp
      - run: python src/scripts/packlunahook.py

      - uses: actions/upload-artifact@v4
        with:
          name: winxp
          path: src/cpp/LunaHook/builds
  
  # build_plugin: (주석 처리된 부분은 그대로 둡니다)
  #   runs-on: windows-latest
  #   strategy:
  #     matrix:
  #       include:
  #         - bits: 32
  #           qtarch: win32_msvc2019
  #         - bits: 64
  #           qtarch: win64_msvc2019_64
  #   permissions:
  #     id-token: write
  #     attestations: write
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
  #       with:
  #         sdk-version: 22621
      
  #     - uses: jurplel/install-qt-action@v3.3.0
  #       with:
  #         version:     5.15.2
  #         host:        windows
  #         target:      desktop
  #         arch:        ${{ matrix.qtarch }}
  #         dir:         ${{ runner.temp }}
  #         setup-python: true
  #     - run: python src/scripts/build_lunahook.py plugin ${{ matrix.bits }}
  #     - run: python src/scripts/packlunahook.py

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: plugin${{ matrix.bits }}
  #         path: src/cpp/LunaHook/builds/plugin${{ matrix.bits }}.zip
  #     - uses: softprops/action-gh-release@v2
  #       with:
  #         tag_name: LunaHook
  #         files: src/cpp/LunaHook/builds/plugin${{ matrix.bits }}.zip
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_x:
    runs-on: windows-latest
    strategy:
      matrix:
        bits: [64]
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 26100
      - run: python src/scripts/build_lunahook.py build x64 0 win7

      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.bits}}
          path: src/cpp/LunaHook/builds
  
  build:
    runs-on: windows-latest
    needs: [build_x,build_xp]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          # 아티팩트 다운로드 경로를 'build'로 변경하여 스크립트가 예상하는 위치와 일치시킵니다.
          path: build 
      - name: List downloaded artifacts for debugging
        run: |
          dir build /s /b # Windows 러너의 경우, 모든 파일과 디렉토리를 재귀적으로 나열합니다.
          # 또는, `tree` 명령어를 사용할 수 있다면:
          # tree build /F
      - run: python src/scripts/build_lunahook.py merge
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: LunaHook
          # 'build_lunahook.py merge' 스크립트가 최종 결과물을 어디에 두는지에 따라 이 'files' 경로를 확인해야 합니다.
          # 만약 병합된 결과물이 여전히 'src/cpp/LunaHook/builds'에 저장된다면 이 경로는 그대로 유지됩니다.
          files: src/cpp/LunaHook/builds/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
